# Generated by Django 3.0.4 on 2020-03-27 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_user_esta_aprobado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('fecha', models.CharField(max_length=50)),
                ('accion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id_Fase', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], default='Abierta', max_length=10, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='User_Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('proyecto_id', models.IntegerField()),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoItem',
            fields=[
                ('id_ti', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('fase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.Fase')),
            ],
            options={
                'ordering': ['nombre'],
                'permissions': (('importar_tipo_item', 'Poder importar Tipo Item'), ('crear_tipo_item', 'Puede crear un Tipo de Item')),
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('CREADO', 'CREADO'), ('INICIADO', 'INICIADO'), ('FINALIZADO', 'FINALIZADO'), ('CANCELADO', 'CANCELADO')], default='CREADO', max_length=10, verbose_name='Estado')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('is_gerente', 'Permiso de gerente de proyectos'), ('is_administradorSistema', 'Permiso de Administrador del sistema')),
            },
        ),
        migrations.CreateModel(
            name='FASE_ROL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Fase')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.AddField(
            model_name='fase',
            name='id_Proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Proyecto'),
        ),
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id_atributo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('es_obligatorio', models.BooleanField(default=True)),
                ('tipo_dato', models.CharField(choices=[('Decimal', 'Decimal'), ('Date', 'Date'), ('File', 'File'), ('String', 'Cadena'), ('Boolean', 'Boolean')], default='Decimal', max_length=8)),
                ('ti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.TipoItem')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
