# Generated by Django 3.0.4 on 2020-03-20 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantida', models.IntegerField()),
            ],
            options={
                'permissions': (('cerrar_fase', 'Cerrar Fases'),),
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('cerrar_proyecto', 'Cerrar Proyectos'),),
            },
        ),
        migrations.CreateModel(
            name='TipoItem',
            fields=[
                ('id_ti', models.AutoField( primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Nombre Para el tipo de Item', help_text='Nombre del Tipo de Item', max_length=20)),
            ],
            options={
                'ordering': ['nombre'],
                'permissions': (('importar_tipo_item', 'Poder importar Tipo Item'), ('crear_tipo_item', 'Puede crear un Tipo de Item')),
            },
        ),
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id_atributo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='atriuto', help_text='Nombre del atributo del Tipo de Item', max_length=20)),
                ('es_obligatorio', models.BooleanField(default=True)),
                ('tipo_dato', models.CharField(choices=[('Decimal', 'Decimal'), ('Date', 'Date'), ('File', 'File'), ('String', 'Cadena'), ('Boolean', 'Boolean')], default='Decimal', max_length=8)),
                ('id_ti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.TipoItem')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
