# Generated by Django 3.0.4 on 2020-04-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributo_item',
            name='idAtributoTI',
            field=models.IntegerField(null=True),
        ),
    ]
