# Generated by Django 3.0.3 on 2020-03-27 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_auto_20200326_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': (('is_gerente', 'Permiso de gerente de proyectos'),)},
        ),
    ]
