# Generated by Django 3.0.3 on 2020-03-24 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_auditoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoria',
            name='proyecto',
        ),
    ]
