# Generated by Django 3.0.4 on 2020-03-28 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_tipoitem_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoitem',
            name='proyecto',
        ),
    ]
