# Generated by Django 3.0.5 on 2020-04-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_lineabase'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='estado',
            field=models.CharField(choices=[('Creado', 'Creado'), ('Aprobado', 'Aprobado'), ('Finalizado', 'Finalizado'), ('En revision', 'En revision')], default='Creado', max_length=20, verbose_name='Estado'),
        ),
    ]
