# Generated by Django 3.0.4 on 2020-03-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_auto_20200320_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoitem',
            name='id_ti',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
