# Generated by Django 3.0.4 on 2020-04-06 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_auto_20200406_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versiones',
            name='id_atributo',
        ),
        migrations.RemoveField(
            model_name='versiones',
            name='id_relacion',
        ),
    ]
