# Generated by Django 3.0.4 on 2020-03-20 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20200320_0516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atributo',
            old_name='id_ti',
            new_name='ti',
        ),
    ]
