# Generated by Django 3.0.3 on 2020-03-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20200327_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': (('is_gerente', 'Permiso de gerente de proyectos'), ('is_administradorSistema', 'Permiso de Administrador del sistema'))},
        ),
    ]
