# Generated by Django 3.0.4 on 2020-04-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_remove_tipoitem_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('crear_item', 'Puede Crear Item'), ('editar_item', 'Puede Editar Item'), ('desactivar_item', 'Puede Desactivar Item'), ('reversionar_item', 'Puede Reversionar Item'), ('aprobar_item', 'Puede Aprobar Item'), ('crear_lb', 'Puede Crear LB'), ('cerrar_lb', 'Puede Cerrar LB'), ('generar_solicitud', 'Puede Generar Solicitud de Cambio')),
                'default_permissions': (),
            },
        ),
    ]
