# Generated by Django 3.0.4 on 2020-04-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20200406_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributo_item',
            name='archivo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
