# Generated by Django 3.0.4 on 2020-04-11 09:31

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_atributo_item_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributo_item',
            name='archivo',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='atributo_item',
            name='valor',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
