# Generated by Django 3.0.5 on 2020-04-22 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20200422_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineabase',
            name='items',
        ),
        migrations.AddField(
            model_name='lineabase',
            name='items',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.Item'),
            preserve_default=False,
        ),
    ]
