# Generated by Django 3.0.3 on 2020-03-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20200324_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_proyecto',
            name='is_valido',
            field=models.BooleanField(default=False),
        ),
    ]
