# Generated by Django 3.0.5 on 2020-04-22 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_auto_20200422_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineabase',
            name='idFase',
        ),
        migrations.RemoveField(
            model_name='lineabase',
            name='items',
        ),
        migrations.CreateModel(
            name='LB_item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Item')),
                ('lb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.LineaBase')),
            ],
        ),
    ]
