# Generated by Django 3.0.3 on 2020-03-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('fecha', models.CharField(max_length=50)),
                ('accion', models.CharField(max_length=100)),
            ],
        ),
    ]
