# Generated by Django 3.0.4 on 2020-03-22 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('gestion', '0005_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id_Fase', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('1', 'Abierta'), ('2', 'Cerrada')], default='Abierta', max_length=10)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Proyecto')),
            ],
            options={
                'verbose_name': 'Fase',
                'verbose_name_plural': 'Fases',
                'ordering': ['id_Fase'],
                'permissions': (('cerrar_fase', 'Puede cerrar Fase'),),
            },
        ),
        migrations.CreateModel(
            name='FASE_ROL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Fase')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.AddField(
            model_name='tipoitem',
            name='fase',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='gestion.Fase'),
        ),
    ]
