# Generated by Django 3.0.3 on 2020-03-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_auto_20200324_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_proyecto',
            name='is_valido',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
