# Generated by Django 3.0.3 on 2020-03-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_auditar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.IntegerField(choices=[(1, 'CREADO'), (2, 'INICIADO')]),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='id_proyecto',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
