# Generated by Django 3.0.4 on 2020-04-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_comite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='Books')),
            ],
        ),
        migrations.AddField(
            model_name='auditoria',
            name='fase',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='id_proyecto',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='proyecto',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
