# Generated by Django 3.0.4 on 2020-03-22 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_auto_20200322_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributo',
            name='ti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.TipoItem'),
        ),
        migrations.AlterField(
            model_name='tipoitem',
            name='fase',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='gestion.Fase'),
        ),
    ]
