# Generated by Django 3.0.3 on 2020-03-25 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0006_auto_20200324_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fase',
            name='id_Fase',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='id_proyecto',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
