# Generated by Django 3.0.3 on 2020-03-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_auto_20200325_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='id_proyecto',
            field=models.AutoField(default=5, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='User_Proyecto',
        ),
    ]
