# Generated by Django 3.0.3 on 2020-03-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_auto_20200325_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='id_proyecto',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
