# Generated by Django 3.0.4 on 2020-03-26 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_auto_20200324_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributo',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='atributo',
            name='ti',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='gestion.TipoItem'),
        ),
        migrations.AlterField(
            model_name='tipoitem',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
