# Generated by Django 3.0.3 on 2020-03-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_auto_20200325_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='id_proyecto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
