# Generated by Django 3.0.4 on 2020-03-26 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_auto_20200326_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributo',
            name='id_atributo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='atributo',
            name='ti',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='gestion.TipoItem'),
        ),
    ]
