# Generated by Django 3.0.3 on 2020-03-25 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0010_auto_20200325_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
