# Generated by Django 3.0.4 on 2020-03-26 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_auto_20200326_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributo',
            name='ti',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.TipoItem'),
        ),
    ]
