# Generated by Django 3.0.3 on 2020-03-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_auto_20200325_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('proyecto_id', models.IntegerField()),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
    ]
