# Generated by Django 3.0.4 on 2020-03-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_auto_20200326_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoitem',
            name='id_ti',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
