# Generated by Django 3.0.4 on 2020-03-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_auto_20200326_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoitem',
            name='id_ti',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
